// Generated by CHUNGUS Compiler
#include "chungus_runtime.h"
#include <stdio.h>
#include <stdlib.h>

int main() {
    ChValue a = ch_int(10);
    ChValue b = ch_int(3);
    ChValue r1 = ch_add(a, b);
    ch_print(r1);
    ChValue r2 = ch_sub(a, b);
    ch_print(r2);
    ChValue r3 = ch_mul(a, b);
    ch_print(r3);
    ChValue r4 = ch_div(a, b);
    ch_print(r4);
    ChValue r5 = ch_idiv(a, b);
    ch_print(r5);
    ChValue r6 = ch_mod(a, b);
    ch_print(r6);
    return 0;
}