#!/usr/bin/env python3
"""
CHUNGUS Runtime Executor

Compiles and executes C code generated by the CHUNGUS compiler.

Usage:
    python -m src.runtime <file.c>
    python -m src.runtime src/codegen/input_codegen.c
"""

import sys
import subprocess
from pathlib import Path


def main():
    """Compile and execute a CHUNGUS-generated C file."""
    
    # Parse arguments
    if len(sys.argv) < 2:
        print("Usage: python -m src.runtime <file.c>")
        print("\nCompiles and executes a C file generated by the CHUNGUS compiler.")
        sys.exit(1)
    
    c_file = Path(sys.argv[1])
    
    if not c_file.exists():
        print(f"Error: C file not found: {c_file}")
        sys.exit(1)
    
    if c_file.suffix != '.c':
        print(f"Error: Expected .c file, got: {c_file}")
        sys.exit(1)
    
    print(f"=== COMPILING {c_file.name} ===")
    
    # Paths
    exe_file = c_file.with_suffix('')
    runtime_c = Path(__file__).parent / "chungus_runtime.c"
    runtime_h_dir = Path(__file__).parent
    
    # Compile command
    compile_cmd = [
        "gcc", "-Wall", "-Wextra",
        f"-I{runtime_h_dir}",
        "-o", str(exe_file),
        str(c_file),
        str(runtime_c),
        "-lm"
    ]
    
    print(f"Command: {' '.join(compile_cmd)}")
    
    try:
        result = subprocess.run(compile_cmd, capture_output=True, text=True, check=True)
        print(f"✓ Compilation successful: {exe_file}")
    except subprocess.CalledProcessError as e:
        print("\nCOMPILATION FAILED:")
        print(e.stderr)
        sys.exit(1)
    
    # Execute
    print(f"\n=== EXECUTING {exe_file.name} ===")
    print()
    
    try:
        result = subprocess.run(
            [f"./{exe_file.name}"],
            capture_output=True,
            text=True,
            check=True,
            cwd=exe_file.parent if exe_file.parent.exists() else "."
        )
        print(result.stdout, end='')
        if result.stderr:
            print(result.stderr, end='', file=sys.stderr)
    except subprocess.CalledProcessError as e:
        print("\nRUNTIME ERROR:")
        print(e.stderr, file=sys.stderr)
        sys.exit(e.returncode)
    
    print("\n✓ Execution complete")


if __name__ == "__main__":
    main()
