// Generated by CHUNGUS Compiler
#include "chungus_runtime.h"
#include <stdio.h>
#include <stdlib.h>

int main() {
    ChValue i = ch_int(0);
    ChValue j = ch_int(1);
    ChValue k = ch_int(2);
    ch_print(i);
    ch_print(j);
    ch_print(k);
    return 0;
}