// Generated by CHUNGUS Compiler
#include "chungus_runtime.h"
#include <stdio.h>
#include <stdlib.h>

int main() {
    ChValue x = ch_int(10);
    ChValue y = ch_int(2);
    ChValue result = ch_div(x, y);
    ch_print(result);
    return 0;
}