// Generated by CHUNGUS Compiler
#include "chungus_runtime.h"
#include <stdio.h>
#include <stdlib.h>

int main() {
    ChValue a = ch_int(8);
    ChValue b = ch_int(3);
    ChValue c = ch_sub(a, b);
    ch_print(c);
    return 0;
}