// Generated by CHUNGUS Compiler
#include "chungus_runtime.h"
#include <stdio.h>
#include <stdlib.h>

int main() {
    ChValue a = ch_int(5);
    ChValue b = ch_int(10);
    ChValue sum = ch_add(a, b);
    ch_print(sum);
    return 0;
}