// Generated by CHUNGUS Compiler
#include "chungus_runtime.h"
#include <stdio.h>
#include <stdlib.h>

int main() {
    ChValue a = ch_int(3);
    ChValue b = ch_int(4);
    ChValue result = ch_mul(a, b);
    ch_print(result);
    return 0;
}