// Generated by CHUNGUS Compiler
#include "chungus_runtime.h"
#include <stdio.h>
#include <stdlib.h>

int main() {
    ChValue first = ch_int(10);
    ChValue second = ch_int(20);
    ChValue third = ch_int(30);
    ch_print(first);
    ch_print(second);
    ch_print(third);
    return 0;
}