// Generated by CHUNGUS Compiler
#include "chungus_runtime.h"
#include <stdio.h>
#include <stdlib.h>

int main() {
    ChValue a = ch_int(5);
    ChValue b = ch_int(3);
    ChValue sum = ch_add(a, b);
    ChValue diff = ch_sub(a, b);
    ChValue prod = ch_mul(a, b);
    ChValue quot = ch_div(a, b);
    ch_print(sum);
    ch_print(diff);
    ch_print(prod);
    ch_print(quot);
    return 0;
}