"""
CHUNGUS Code Generator - Converts type-annotated AST to C code.

This module implements the code generation phase of the CHUNGUS compiler.
It receives a fully type-checked and annotated AST from semantic analysis
and generates C code using the CHUNGUS runtime library.
"""

from typing import Optional, List, Dict
from dataclasses import dataclass
from src.constants.ast import ASTNode
from src.semantic.semantic_analyzer import SymbolTable


@dataclass
class CodeGenResult:
    """Result of code generation."""
    code: Optional[str]       # Generated code or None if failed
    errors: List[str]          # Error messages
    success: bool              # True if generation succeeded


class CodeGenerator:
    """
    Main code generator class for C code generation.
    
    Consumes a type-annotated AST and produces C code using the CHUNGUS runtime library.
    Uses the visitor pattern to traverse AST nodes and emit code.
    """
    
    def __init__(self, ast: ASTNode, source: str = "", symbol_table: Optional[SymbolTable] = None, debug: bool = False):
        """
        Initialize the code generator.
        
        Args:
            ast: Root AST node (type-annotated by semantic analyzer)
            source: Source code (for error reporting)
            symbol_table: Symbol table from semantic analysis (optional)
            debug: Enable debug output
        """
        self._ast = ast
        self._lines = source.splitlines(keepends=False)  # source code split per newline
        self._symbol_table = symbol_table
        self._debug = debug
        self._errors: List[str] = []
        self._output: List[str] = []  # Generated code lines
        self._indent_level = 0
        self._in_function = False  # Track if we're inside a function
        self._temp_counter = 0  # For generating temporary variables

    def generate(self) -> CodeGenResult:
        """
        Generate executable code from the AST.
        
        Returns:
            CodeGenResult with generated code or errors
        """
        if self._debug:
            print("=== CODE GENERATION STARTED ===")
            print(f"AST Root: {self._ast.kind}")

        try:
            # Visit root node
            self._visit(self._ast)

            if self._errors:
                return CodeGenResult(
                    code=None,
                    errors=self._errors,
                    success=False
                )
            
            # Join generated code lines
            generated_code = "\n".join(self._output)
            
            if self._debug:
                print("=== CODE GENERATION COMPLETE ===")
                print(generated_code)
            
            return CodeGenResult(
                code=generated_code,
                errors=[],
                success=True
            )
            
        except Exception as e:
            error_msg = f"Code generation failed: {str(e)}"
            self._errors.append(error_msg)
            return CodeGenResult(
                code=None,
                errors=self._errors,
                success=False
            )

    def _visit(self, node: Optional[ASTNode]) -> Optional[str]:
        """
        Visit an AST node and generate code.
        
        Returns the generated expression code for expression nodes,
        or None for statement nodes (which emit code directly).
        
        Uses dynamic dispatch to call appropriate visitor method.
        """
        if node is None:
            return None

        # Map operator symbols to method names
        operator_map = {
            "+": "add",
            "-": "sub",
            "*": "mul",
            "/": "div",
            "//": "idiv",
            "%": "mod",
            "**": "pow",
            "<": "less",
            ">": "greater",
            "<=": "le",
            ">=": "ge",
            "==": "eq",
            "!=": "ne",
            "and": "and",
            "or": "or",
            "!": "not"
        }

        # Get method name, mapping operators
        if node.kind in operator_map:
            method_name = f"_visit_{operator_map[node.kind]}"
        else:
            method_name = f"_visit_{node.kind}"
        
        visitor = getattr(self, method_name, self._visit_default)
        return visitor(node)

    def _visit_default(self, node: ASTNode) -> None:
        """
        Default visitor for nodes without specific handlers.
        Recursively visits children.
        """
        if self._debug:
            print(f"Visiting (default): {node.kind}")
        
        for child in node.children:
            self._visit(child)
        return None
    
    def _visit_program(self, node: ASTNode) -> None:
        """Visit program root node - generates complete C program."""
        if self._debug:
            print("Visiting: program")
        
        # Emit C program header
        self._emit("// Generated by CHUNGUS Compiler")
        self._emit("#include \"chungus_runtime.h\"")
        self._emit("#include <stdio.h>")
        self._emit("#include <stdlib.h>")
        self._emit("")

        # Separate functions from main statements
        functions = [child for child in node.children if child.kind == "function"]
        main_stmts = [child for child in node.children if child.kind != "function"]

        # Generate forward declarations for functions
        for func in functions:
            func_name = func.value
            self._emit(f"ChValue {func_name}();  // Forward declaration")
        
        if functions:
            self._emit("")
        
        # Generate function definitions
        for func in functions:
            self._visit(func)
            self._emit("")
        
        # Generate main function
        self._emit("int main() {")
        self._indent()
        
        # Visit main statements
        for stmt in main_stmts:
            self._visit(stmt)
        
        self._emit("return 0;")
        self._dedent()
        self._emit("}")
        
        return None
    
    def _emit(self, code: str = "") -> None:
        """
        Emit a line of code with proper indentation.
        
        Args:
            code: Code line to emit (without indentation)
        """
        if code:
            indent = "    " * self._indent_level
            self._output.append(indent + code)
        else:
            self._output.append("")
    
    def _indent(self) -> None:
        """Increase indentation level."""
        self._indent_level += 1
    
    def _dedent(self) -> None:
        """Decrease indentation level."""
        if self._indent_level > 0:
            self._indent_level -= 1
    
    def _error(self, message: str, node: Optional[ASTNode] = None) -> None:
        """
        Record a code generation error.
        
        Args:
            message: Error message
            node: AST node where error occurred (for location info)
        """
        if node and node.line is not None:
            error = f"Line {node.line}: {message}"
        else:
            error = message
        
        self._errors.append(error)
        
        if self._debug:
            print(f"ERROR: {error}")

    def _gen_temp(self) -> str:
        """Generate a unique temporary variable name."""
        temp = f"_t{self._temp_counter}"
        self._temp_counter += 1
        return temp
    
    # ==================== LITERAL VISITORS ====================
    
    def _visit_int_literal(self, node: ASTNode) -> str:
        """Generate code for integer literal."""
        value = node.value
        # Handle CHUNGUS negative syntax: ~5 means -5
        if value.startswith('~'):
            value = '-' + value[1:]
        return f"ch_int({value})"
    
    def _visit_float_literal(self, node: ASTNode) -> str:
        """Generate code for float literal."""
        value = node.value
        # Handle CHUNGUS negative syntax: ~3.14 means -3.14
        if value.startswith('~'):
            value = '-' + value[1:]
        return f"ch_float({value})"
    
    def _visit_bool_literal(self, node: ASTNode) -> str:
        """Generate code for boolean literal."""
        # Accept both lowercase (true/false) and uppercase (TRUE/FALSE)
        # to match lexer/parser outputs and avoid silently flipping to false.
        lexeme = (node.value or "").strip().lower()
        c_bool = "true" if lexeme == "true" else "false"
        return f"ch_bool({c_bool})"
    
    def _visit_str_literal(self, node: ASTNode) -> str:
        """Generate code for string literal."""
        # CHUNGUS uses 'string' but C needs "string"
        # Remove the CHUNGUS quotes and add C quotes
        chungus_str = node.value
        if chungus_str.startswith("'") and chungus_str.endswith("'"):
            # Remove single quotes and add double quotes for C
            c_str = chungus_str[1:-1]  # Remove surrounding quotes
            # Escape any double quotes in the string
            c_str = c_str.replace('"', '\\"')
            return f'ch_str("{c_str}")'
        return f"ch_str({chungus_str})"
    
    def _visit_id(self, node: ASTNode) -> str:
        """Generate code for identifier."""
        return node.value
    
    def _visit_read(self, node: ASTNode) -> str:
        """Generate code for read statement."""
        return "ch_read()"
    
    # ==================== ASSIGNMENT VISITORS ====================
    
    def _visit_assignment_statement(self, node: ASTNode) -> None:
        """Generate code for assignment statement."""
        var_name = node.value
        rhs_code = self._visit(node.children[0]) if node.children else "ch_int(0)"
        
        # Check if this is a declaration or reassignment
        if hasattr(node, 'is_declaration') and node.is_declaration:
            # First assignment - declare variable
            self._emit(f"ChValue {var_name} = {rhs_code};")
        else:
            # Reassignment - just assign
            self._emit(f"{var_name} = {rhs_code};")
    
    # ==================== EXPRESSION VISITORS ====================
    
    def _visit_binary_op(self, node: ASTNode, op: str, func: str) -> str:
        """Helper for binary operations."""
        left_code = self._visit(node.children[0]) if node.children else "ch_int(0)"
        right_code = self._visit(node.children[1]) if len(node.children) > 1 else "ch_int(0)"

        # it would be something like ch_add(_ , _)
        return f"{func}({left_code}, {right_code})"
    
    # Arithmetic operators
    def _visit_add(self, node: ASTNode) -> str:
        """Generate code for addition (+)."""
        return self._visit_binary_op(node, "+", "ch_add")
    
    def _visit_sub(self, node: ASTNode) -> str:
        """Generate code for subtraction (-)."""
        return self._visit_binary_op(node, "-", "ch_sub")
    
    def _visit_mul(self, node: ASTNode) -> str:
        """Generate code for multiplication (*)."""
        return self._visit_binary_op(node, "*", "ch_mul")
    
    def _visit_div(self, node: ASTNode) -> str:
        """Generate code for division (/)."""
        return self._visit_binary_op(node, "/", "ch_div")
    
    def _visit_idiv(self, node: ASTNode) -> str:
        """Generate code for integer division (//)."""
        return self._visit_binary_op(node, "//", "ch_idiv")
    
    def _visit_mod(self, node: ASTNode) -> str:
        """Generate code for modulo (%)."""
        return self._visit_binary_op(node, "%", "ch_mod")
    
    def _visit_pow(self, node: ASTNode) -> str:
        """Generate code for power (^)."""
        return self._visit_binary_op(node, "^", "ch_pow")
    
    # Comparison operators
    def _visit_less(self, node: ASTNode) -> str:
        """Generate code for less than (<)."""
        return self._visit_binary_op(node, "<", "ch_less")
    
    def _visit_greater(self, node: ASTNode) -> str:
        """Generate code for greater than (>)."""
        return self._visit_binary_op(node, ">", "ch_greater")
    
    def _visit_le(self, node: ASTNode) -> str:
        """Generate code for less than or equal (<=)."""
        return self._visit_binary_op(node, "<=", "ch_le")
    
    def _visit_ge(self, node: ASTNode) -> str:
        """Generate code for greater than or equal (>=)."""
        return self._visit_binary_op(node, ">=", "ch_ge")
    
    def _visit_eq(self, node: ASTNode) -> str:
        """Generate code for equality (==)."""
        return self._visit_binary_op(node, "==", "ch_eq")
    
    def _visit_ne(self, node: ASTNode) -> str:
        """Generate code for inequality (!=)."""
        return self._visit_binary_op(node, "!=", "ch_ne")
    
    # Logical operators
    def _visit_and(self, node: ASTNode) -> str:
        """Generate code for logical AND (&)."""
        return self._visit_binary_op(node, "&", "ch_and")
    
    def _visit_or(self, node: ASTNode) -> str:
        """Generate code for logical OR (|)."""
        return self._visit_binary_op(node, "|", "ch_or")
    
    def _visit_not(self, node: ASTNode) -> str:
        """Generate code for logical NOT (!)."""
        operand_code = self._visit(node.children[0]) if node.children else "ch_bool(false)"
        return f"ch_not({operand_code})"
    
    # ==================== OUTPUT VISITOR ====================

    def _visit_output_statement(self, node: ASTNode) -> None:
        """Generate code for output/show statement."""
        if not node.children:
            self._emit("ch_print(ch_int(0));")
            return

        child = node.children[0]
        expr_code = self._visit(child)

        # If the expression is a plain variable reference (id), print it
        # directly — we must NOT free it because the variable still owns
        # that memory and may be used later.
        #
        # For everything else (literals, function calls, binary ops, etc.)
        # the result is a temporary ChValue.  String temporaries hold a
        # strdup-allocated pointer that would leak without an explicit free.
        # ch_free is safe for all types (no-op for int/float/bool).
        if child.kind == "id":
            self._emit(f"ch_print({expr_code});")
        else:
            temp = self._gen_temp()
            self._emit(f"ChValue {temp} = {expr_code};")
            self._emit(f"ch_print({temp});")
            self._emit(f"ch_free(&{temp});")

    # ==================== CONTROL FLOW VISITORS ====================
    
    def _visit_conditional_block(self, node: ASTNode) -> None:
        """Generate code for if/elif/else block."""
        for child in node.children:
            self._visit(child)
    
    def _visit_if(self, node: ASTNode) -> None:
        """Generate code for if statement."""
        # children = [condition, ...body_statements]
        cond_code = self._visit(node.children[0]) if node.children else "ch_bool(false)"
        
        self._emit(f"if (ch_to_bool({cond_code})) {{")
        self._indent()
        
        # Visit body statements
        for stmt in node.children[1:]:
            self._visit(stmt)
        
        self._dedent()
        self._emit("}")
    
    def _visit_elif(self, node: ASTNode) -> None:
        """Generate code for elif statement."""
        # children = [condition, ...body_statements]
        cond_code = self._visit(node.children[0]) if node.children else "ch_bool(false)"
        
        self._emit(f"else if (ch_to_bool({cond_code})) {{")
        self._indent()
        
        # Visit body statements
        for stmt in node.children[1:]:
            self._visit(stmt)
        
        self._dedent()
        self._emit("}")
    
    def _visit_else(self, node: ASTNode) -> None:
        """Generate code for else statement."""
        self._emit("else {")
        self._indent()
        
        # Visit body statements
        for stmt in node.children:
            self._visit(stmt)
        
        self._dedent()
        self._emit("}")

    def _visit_for(self, node: ASTNode) -> None:
        """Generate code for for loop.

        AST contract from parser:
            node.value = loop variable name
            node.children = [range_expr_1..3, general_statement...]

        Supported forms:
            range(stop)
            range(start, stop)
            range(start, stop, step)
        """
        loop_var = node.value or "_i"

        # Body statements are wrapped as `general_statement` nodes. while range expr are not.
        body_start = len(node.children)
        for i, child in enumerate(node.children):
            if child.kind == "general_statement":
                body_start = i
                break

        range_nodes = node.children[:body_start]
        body_nodes = node.children[body_start:]

        # Parse range args with Python-like defaults.
        # range(stop) -> start=0, step=1
        # range(start, stop) -> step=1
        # range(start, stop, step)
        if len(range_nodes) == 1:
            start_expr = "ch_int(0)"
            stop_expr = self._visit(range_nodes[0])
            step_expr = "ch_int(1)"
        elif len(range_nodes) == 2:
            start_expr = self._visit(range_nodes[0])
            stop_expr = self._visit(range_nodes[1])
            step_expr = "ch_int(1)"
        else:
            start_expr = self._visit(range_nodes[0]) if len(range_nodes) > 0 else "ch_int(0)"
            stop_expr = self._visit(range_nodes[1]) if len(range_nodes) > 1 else "ch_int(0)"
            step_expr = self._visit(range_nodes[2]) if len(range_nodes) > 2 else "ch_int(1)"

        # Use unique temporaries so nested loops are safe.
        t_start = self._gen_temp() + "_start"
        t_stop = self._gen_temp() + "_stop"
        t_step = self._gen_temp() + "_step"

        self._emit("{")
        self._indent()
        # initialize range expr vars
        self._emit(f"int {t_start} = (int)ch_to_number({start_expr});")
        self._emit(f"int {t_stop} = (int)ch_to_number({stop_expr});")
        self._emit(f"int {t_step} = (int)ch_to_number({step_expr});")
        self._emit("")
        # handle 0 step
        self._emit(f"if ({t_step} == 0) {{")
        self._indent()
        self._emit('fprintf(stderr, "Runtime Error: range() step cannot be zero\\n");')
        self._dedent()
        self._emit("} else {")
        self._indent()
        # initialize loop variable
        self._emit(f"ChValue {loop_var} = ch_int({t_start});")

        # step > 0 → continue while loop_var < stop
        # step < 0 → continue while loop_var > stop
        self._emit(
            f"while (({t_step} > 0) ? ((int)ch_to_number({loop_var}) < {t_stop}) : ((int)ch_to_number({loop_var}) > {t_stop})) {{"
        )
        self._indent()

        for stmt in body_nodes:
            self._visit(stmt)

        self._emit(f"{loop_var} = ch_int((int)ch_to_number({loop_var}) + {t_step});")
        self._dedent()
        self._emit("}")
        self._emit(f"ch_free(&{loop_var});")
        self._dedent()
        self._emit("}")
        self._dedent()
        self._emit("}")
    
    def _visit_while(self, node: ASTNode) -> None:
        """Generate code for while loop."""
        # children = [condition, ...body_statements]
        cond_code = self._visit(node.children[0]) if node.children else "ch_bool(false)"
        
        self._emit(f"while (ch_to_bool({cond_code})) {{")
        self._indent()
        
        # Visit body statements
        for stmt in node.children[1:]:
            self._visit(stmt)
        
        self._dedent()
        self._emit("}")
    
    def _visit_todo(self, node: ASTNode) -> None:
        """Generate code for todo statement."""
        msg = node.value if node.value else "not implemented"
        self._emit(f"// TODO: {msg}")