"""
CHUNGUS Code Generator - Converts type-annotated AST to executable code.

This module implements the code generation phase of the CHUNGUS compiler.
It receives a fully type-checked and annotated AST from semantic analysis
and generates executable output (initially Python code, potentially bytecode later).
"""

from typing import Optional, List
from dataclasses import dataclass
from src.constants.ast import ASTNode
from src.semantic.semantic_analyzer import SymbolTable


@dataclass
class CodeGenResult:
    """Result of code generation."""
    code: Optional[str]       # Generated code or None if failed
    errors: List[str]          # Error messages
    success: bool              # True if generation succeeded


class CodeGenerator:
    """
    Main code generator class.
    
    Consumes a type-annotated AST and produces executable code.
    Uses the visitor pattern to traverse AST nodes and emit code.
    """
    
    def __init__(self, ast: ASTNode, source: str = "", symbol_table: Optional[SymbolTable] = None, debug: bool = False):
        """
        Initialize the code generator.
        
        Args:
            ast: Root AST node (type-annotated by semantic analyzer)
            source: Original source code (for error reporting)
            symbol_table: Symbol table from semantic analysis (optional)
            debug: Enable debug output
        """
        self._ast = ast
        self._lines = source.splitlines(keepends=False)  # source code split per newline
        self._symbol_table = symbol_table
        self._debug = debug
        self._errors: List[str] = []
        self._output: List[str] = []  # Generated code lines
        self._indent_level = 0
        
    def generate(self) -> CodeGenResult:
        """
        Generate executable code from the AST.
        
        Returns:
            CodeGenResult with generated code or errors
        """
        if self._debug:
            print("=== CODE GENERATION STARTED ===")
            print(f"AST Root: {self._ast.kind}")
        
        try:
            # Visit root node
            self._visit(self._ast)
            
            if self._errors:
                return CodeGenResult(
                    code=None,
                    errors=self._errors,
                    success=False
                )
            
            # Join generated code lines
            generated_code = "\n".join(self._output)
            
            if self._debug:
                print("=== CODE GENERATION COMPLETE ===")
                print(generated_code)
            
            return CodeGenResult(
                code=generated_code,
                errors=[],
                success=True
            )
            
        except Exception as e:
            error_msg = f"Code generation failed: {str(e)}"
            self._errors.append(error_msg)
            return CodeGenResult(
                code=None,
                errors=self._errors,
                success=False
            )

    def _visit(self, node: Optional[ASTNode]) -> None:
        """
        Visit an AST node and generate code.
        
        Uses dynamic dispatch to call appropriate visitor method.
        """
        if node is None:
            return
        
        # Dynamic dispatch to visitor method
        method_name = f"_visit_{node.kind}"
        visitor = getattr(self, method_name, self._visit_default)
        visitor(node)
    
    def _visit_default(self, node: ASTNode) -> None:
        """
        Default visitor for nodes without specific handlers.
        Recursively visits children.
        """
        if self._debug:
            print(f"Visiting (default): {node.kind}")
        
        for child in node.children:
            self._visit(child)
    
    def _visit_program(self, node: ASTNode) -> None:
        """Visit program root node."""
        if self._debug:
            print("Visiting: program")
        
        # Emit Python header comment
        self._emit("# Generated by CHUNGUS Compiler")
        self._emit("# Type-annotated AST received from semantic analyzer")
        self._emit("")
        
        # Visit all children (functions and main statements)
        for child in node.children:
            self._visit(child)
    
    def _emit(self, code: str = "") -> None:
        """
        Emit a line of code with proper indentation.
        
        Args:
            code: Code line to emit (without indentation)
        """
        if code:
            indent = "    " * self._indent_level
            self._output.append(indent + code)
        else:
            self._output.append("")
    
    def _indent(self) -> None:
        """Increase indentation level."""
        self._indent_level += 1
    
    def _dedent(self) -> None:
        """Decrease indentation level."""
        if self._indent_level > 0:
            self._indent_level -= 1
    
    def _error(self, message: str, node: Optional[ASTNode] = None) -> None:
        """
        Record a code generation error.
        
        Args:
            message: Error message
            node: AST node where error occurred (for location info)
        """
        if node and node.line is not None:
            error = f"Line {node.line}: {message}"
        else:
            error = message
        
        self._errors.append(error)
        
        if self._debug:
            print(f"ERROR: {error}")
